BEGIN TRANSACTION;
DROP TABLE IF EXISTS Questions;
CREATE TABLE Questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  original_id TEXT,
  discipline TEXT,
  question TEXT,
  options TEXT,
  answer TEXT,
  explanation TEXT,
  banca TEXT,
  pegadinha TEXT,
  content_id INTEGER DEFAULT 1
);

INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('1', 'Português', '**Texto base — Questões 01 a 04**
*"A administração pública, em sua busca incessante pela eficiência, depara-se com o desafio perene de conciliar a celeridade dos processos com a segurança jurídica que o cidadão espera. A rigidez excessiva, muitas vezes confundida com legalidade, pode converter-se em obstáculo intransponível para a entrega de serviços de qualidade. Por outro lado, a flexibilidade desmedida, sem os freios e contrapesos institucionais, abre espaço para a discricionariedade arbitrária. O ponto de equilíbrio, ainda que movediço, reside na gestão orientada por resultados, pautada pela transparência e pela participação social, que não apenas legitimam as ações do Estado, mas também as aprimoram continuamente."*

---

A ideia central do texto é que:', '[{"letra":"A","texto":"A legalidade e a eficiência são princípios antagônicos e inconciliáveis na gestão pública.","correta":false},{"letra":"B","texto":"A administração pública deve abandonar a rigidez burocrática em prol de uma flexibilidade total.","correta":false},{"letra":"C","texto":"O desafio da administração é equilibrar a agilidade processual com a segurança jurídica, por meio da gestão orientada a resultados.","correta":true},{"letra":"D","texto":"O principal obstáculo para a qualidade dos serviços públicos é a participação social, que retarda as decisões.","correta":false},{"letra":"E","texto":"A segurança jurídica é um valor superado na administração pública contemporânea, devendo ser substituída pela celeridade.","correta":false}]', 'C', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"O desafio da administração é equilibrar a agilidade processual com a segurança jurídica, por meio da gestão orientada a resultados."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('2', 'Português', '**Texto base — Questões 01 a 04**
*"A administração pública, em sua busca incessante pela eficiência, depara-se com o desafio perene de conciliar a celeridade dos processos com a segurança jurídica que o cidadão espera. A rigidez excessiva, muitas vezes confundida com legalidade, pode converter-se em obstáculo intransponível para a entrega de serviços de qualidade. Por outro lado, a flexibilidade desmedida, sem os freios e contrapesos institucionais, abre espaço para a discricionariedade arbitrária. O ponto de equilíbrio, ainda que movediço, reside na gestão orientada por resultados, pautada pela transparência e pela participação social, que não apenas legitimam as ações do Estado, mas também as aprimoram continuamente."*

---

A palavra **"perene"** (L.1) pode ser substituída, sem alteração de sentido no contexto, por:', '[{"letra":"A","texto":"Irrelevante.","correta":false},{"letra":"B","texto":"Temporário.","correta":false},{"letra":"C","texto":"Incessante.","correta":true},{"letra":"D","texto":"Inconstante.","correta":false},{"letra":"E","texto":"Opcional.","correta":false}]', 'C', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Incessante."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('3', 'Português', '**Texto base — Questões 01 a 04**
*"A administração pública, em sua busca incessante pela eficiência, depara-se com o desafio perene de conciliar a celeridade dos processos com a segurança jurídica que o cidadão espera. A rigidez excessiva, muitas vezes confundida com legalidade, pode converter-se em obstáculo intransponível para a entrega de serviços de qualidade. Por outro lado, a flexibilidade desmedida, sem os freios e contrapesos institucionais, abre espaço para a discricionariedade arbitrária. O ponto de equilíbrio, ainda que movediço, reside na gestão orientada por resultados, pautada pela transparência e pela participação social, que não apenas legitimam as ações do Estado, mas também as aprimoram continuamente."*

---

No trecho *"pautada pela transparência e pela participação social, que não apenas legitimam as ações do Estado, mas também as aprimoram continuamente"*, o pronome **"as"** retoma o termo:', '[{"letra":"A","texto":"Transparência e participação social.","correta":false},{"letra":"B","texto":"Ações do Estado.","correta":true},{"letra":"C","texto":"Resultados.","correta":false},{"letra":"D","texto":"Estado.","correta":false},{"letra":"E","texto":"Transparência.","correta":false}]', 'B', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Ações do Estado."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('4', 'Português', '**Texto base — Questões 01 a 04**
*"A administração pública, em sua busca incessante pela eficiência, depara-se com o desafio perene de conciliar a celeridade dos processos com a segurança jurídica que o cidadão espera. A rigidez excessiva, muitas vezes confundida com legalidade, pode converter-se em obstáculo intransponível para a entrega de serviços de qualidade. Por outro lado, a flexibilidade desmedida, sem os freios e contrapesos institucionais, abre espaço para a discricionariedade arbitrária. O ponto de equilíbrio, ainda que movediço, reside na gestão orientada por resultados, pautada pela transparência e pela participação social, que não apenas legitimam as ações do Estado, mas também as aprimoram continuamente."*

---

A relação de sentido estabelecida pela conjunção **"Por outro lado"** (L.4) é de:', '[{"letra":"A","texto":"Adição.","correta":false},{"letra":"B","texto":"Conclusão.","correta":false},{"letra":"C","texto":"Explicação.","correta":false},{"letra":"D","texto":"Oposição.","correta":true},{"letra":"E","texto":"Condição.","correta":false}]', 'D', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Oposição."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('5', 'Português', 'Assinale a alternativa em que a palavra está grafada de acordo com o Acordo Ortográfico vigente:', '[{"letra":"A","texto":"vôo","correta":false},{"letra":"B","texto":"enjôo","correta":false},{"letra":"C","texto":"abençôo","correta":false},{"letra":"D","texto":"voo","correta":true},{"letra":"E","texto":"crêem","correta":false}]', 'D', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"voo"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.

💡 **Dica Extra:** Foque na perda do acento em ditongos abertos paroxítonos (ideia, jiboia) e nos hiatos (voo, leem).', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('6', 'Português', 'Assinale a alternativa em que o acento indicador de crase foi empregado **corretamente**:', '[{"letra":"A","texto":"O funcionário foi à referida reunião.","correta":true},{"letra":"B","texto":"Ele sempre se referiu à Vossa Senhoria com respeito.","correta":false},{"letra":"C","texto":"Chegamos à noite, após uma longa viagem.","correta":false},{"letra":"D","texto":"A reunião estava à terminar quando cheguei.","correta":false},{"letra":"E","texto":"Oferecemos o suporte à todos os usuários.","correta":false}]', 'A', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"O funcionário foi à referida reunião."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('7', 'Português', 'Assinale a opção em que a concordância verbal está **em desacordo** com a norma padrão:', '[{"letra":"A","texto":"Haviam muitos candidatos na sala de espera.","correta":true},{"letra":"B","texto":"Fazem três anos que ele não trabalha no órgão.","correta":false},{"letra":"C","texto":"Mais de um servidor se candidatou à vaga.","correta":false},{"letra":"D","texto":"Fui eu quem resolveu o problema.","correta":false},{"letra":"E","texto":"Os Estados Unidos é um país influente.","correta":false}]', 'A', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Haviam muitos candidatos na sala de espera."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('8', 'Português', 'Em qual alternativa a regência verbal está de acordo com a norma culta?', '[{"letra":"A","texto":"O servidor visava o cargo de assessor.","correta":false},{"letra":"B","texto":"Ela prefere café do que chá.","correta":false},{"letra":"C","texto":"Informei-lhe de que o prazo venceria amanhã.","correta":false},{"letra":"D","texto":"O diretor assistiu ao servidor durante a reunião.","correta":true},{"letra":"E","texto":"O funcionário obedeceu o regulamento interno.","correta":false}]', 'D', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"O diretor assistiu ao servidor durante a reunião."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('9', 'Português', '*"O Ministério da Fazenda divulgou o edital do concurso."* Transformando para a voz passiva analítica, obtém-se:', '[{"letra":"A","texto":"Divulgou-se o edital do concurso pelo Ministério da Fazenda.","correta":false},{"letra":"B","texto":"O edital do concurso foi divulgado pelo Ministério da Fazenda.","correta":true},{"letra":"C","texto":"O edital do concurso divulgou-se.","correta":false},{"letra":"D","texto":"O Ministério da Fazenda foi divulgado pelo edital do concurso.","correta":false},{"letra":"E","texto":"Divulgou o edital do concurso o Ministério da Fazenda.","correta":false}]', 'B', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"O edital do concurso foi divulgado pelo Ministério da Fazenda."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('10', 'Português', 'Em *"O candidato que estuda com disciplina tem mais chances de sucesso"*, o pronome relativo **"que"** retoma o termo:', '[{"letra":"A","texto":"Sucesso.","correta":false},{"letra":"B","texto":"Disciplina.","correta":false},{"letra":"C","texto":"Chances.","correta":false},{"letra":"D","texto":"Candidato.","correta":true},{"letra":"E","texto":"Mais.","correta":false}]', 'D', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Candidato."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('11', 'Português', 'Em *"Os servidores discutiram a proposta durante horas"*, o verbo destacado classifica-se como:', '[{"letra":"A","texto":"Verbo transitivo direto.","correta":true},{"letra":"B","texto":"Verbo transitivo indireto.","correta":false},{"letra":"C","texto":"Verbo intransitivo.","correta":false},{"letra":"D","texto":"Verbo de ligação.","correta":false},{"letra":"E","texto":"Verbo transitivo direto e indireto.","correta":false}]', 'A', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Verbo transitivo direto."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('12', 'Português', '*"O relatório foi revisado **minuciosamente** pelo chefe."* A palavra em destaque exerce a função de:', '[{"letra":"A","texto":"Adjunto adnominal.","correta":false},{"letra":"B","texto":"Complemento nominal.","correta":false},{"letra":"C","texto":"Adjunto adverbial de modo.","correta":true},{"letra":"D","texto":"Adjunto adverbial de intensidade.","correta":false},{"letra":"E","texto":"Predicativo do sujeito.","correta":false}]', 'C', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Adjunto adverbial de modo."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('13', 'Português', 'Aponte a alternativa em que a oração destacada expressa uma ideia de **finalidade**:', '[{"letra":"A","texto":"O servidor trabalhou para que o projeto fosse concluído.","correta":true},{"letra":"B","texto":"Como estava cansado, o servidor foi para casa.","correta":false},{"letra":"C","texto":"Embora estivesse doente, compareceu ao trabalho.","correta":false},{"letra":"D","texto":"A eficiência é tão importante quanto a legalidade.","correta":false},{"letra":"E","texto":"Se houver um acordo, o processo andará mais rápido.","correta":false}]', 'A', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"O servidor trabalhou para que o projeto fosse concluído."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('14', 'Português', 'Assinale a alternativa em que o termo entre parênteses **não** corresponde a uma figura de linguagem presente no trecho:', '[{"letra":"A","texto":"*\"A rigidez excessiva... pode converter-se em obstáculo intransponível.\"* (Metáfora)","correta":false},{"letra":"B","texto":"*\"O ponto de equilíbrio, ainda que movediço, reside na gestão orientada por resultados.\"* (Antítese)","correta":true},{"letra":"C","texto":"*\"A administração pública, em sua busca incessante pela eficiência...\"* (Prosopopeia)","correta":false},{"letra":"D","texto":"*\"O servidor é uma formiga trabalhando.\"* (Comparação)","correta":false},{"letra":"E","texto":"*\"Sua boca é um sepulcro.\"* (Metáfora)","correta":false}]', 'B', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"*"O ponto de equilíbrio, ainda que movediço, reside na gestão orientada por resultados."* (Antítese)"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('15', 'Português', 'De acordo com o Manual de Redação da Presidência da República, a comunicação interna entre unidades de um mesmo órgão público deve ser feita por meio de:', '[{"letra":"A","texto":"Ofício","correta":true},{"letra":"B","texto":"Aviso","correta":false},{"letra":"C","texto":"Memorando","correta":false},{"letra":"D","texto":"Mensagem","correta":false},{"letra":"E","texto":"Exposição de Motivos","correta":false}]', 'A', '[GABARITO CORRIGIDO] Segundo a 3ª edição do Manual de Redação da Presidência da República (2018), os padrões ''Memorando'' e ''Aviso'' foram abolidos. Toda comunicação oficial (seja interna ou externa) agora utiliza o padrão único chamado **Ofício**.', 'ESAF', 'Bancas usam material antigo para confundir alunos sobre o finado ''Memorando''. Memorize a extinção dele pelo MRPR de 2018.', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('16', 'Português', 'A característica da redação oficial que preza pela objetividade, sem palavras ou ideias desnecessárias, é denominada:', '[{"letra":"A","texto":"Impessoalidade.","correta":false},{"letra":"B","texto":"Concisão.","correta":true},{"letra":"C","texto":"Clareza.","correta":false},{"letra":"D","texto":"Uniformidade.","correta":false},{"letra":"E","texto":"Formalidade.","correta":false}]', 'B', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Concisão."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('17', 'Português', 'Assinale a alternativa em que a palavra está **corretamente acentuada**:', '[{"letra":"A","texto":"eletrecidade","correta":false},{"letra":"B","texto":"viuvez","correta":false},{"letra":"C","texto":"ítem","correta":false},{"letra":"D","texto":"órfão","correta":true},{"letra":"E","texto":"graúdo","correta":false}]', 'D', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"órfão"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('18', 'Português', 'Em *"A candidata estava a uma hora do local da prova a espera do resultado"*, o emprego do "a" se classifica, respectivamente, como:', '[{"letra":"A","texto":"Artigo, preposição, preposição.","correta":true},{"letra":"B","texto":"Preposição, artigo, preposição.","correta":false},{"letra":"C","texto":"Artigo, preposição, artigo.","correta":false},{"letra":"D","texto":"Artigo, artigo, preposição.","correta":false},{"letra":"E","texto":"Preposição, preposição, preposição.","correta":false}]', 'A', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"Artigo, preposição, preposição."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('19', 'Português', 'Assinale a alternativa que apresenta um exemplo de **predicado verbo-nominal**:', '[{"letra":"A","texto":"O servidor saiu.","correta":false},{"letra":"B","texto":"O servidor parecia cansado.","correta":false},{"letra":"C","texto":"O servidor chegou cansado.","correta":true},{"letra":"D","texto":"O servidor é eficiente.","correta":false},{"letra":"E","texto":"O servidor trabalha muito.","correta":false}]', 'C', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"O servidor chegou cansado."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('20', 'Português', 'Em *"A administração é a arte de realizar com eficiência"*, o verbo destacado:', '[{"letra":"A","texto":"É de ação e exige complemento.","correta":false},{"letra":"B","texto":"É de ligação e liga o sujeito a uma característica.","correta":true},{"letra":"C","texto":"É intransitivo e indica estado permanente.","correta":false},{"letra":"D","texto":"É transitivo direto e indica ação.","correta":false},{"letra":"E","texto":"É transitivo indireto e indica posse.","correta":false}]', 'B', 'De acordo com a regra gramatical e coerência textual, a resolução aponta para a alternativa correta: **"É de ligação e liga o sujeito a uma característica."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('21', 'Matemática e Raciocínio Lógico', 'Em um concurso, a razão entre candidatos inscritos e vagas é de 200:1. Se 2.500 vagas fossem ofertadas, quantos candidatos estariam inscritos?', '[{"letra":"A","texto":"250.000","correta":false},{"letra":"B","texto":"400.000","correta":false},{"letra":"C","texto":"500.000","correta":true},{"letra":"D","texto":"525.000","correta":false},{"letra":"E","texto":"575.000","correta":false}]', 'C', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"500.000"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('22', 'Matemática e Raciocínio Lógico', 'Um servidor recebeu um aumento de 12% sobre seu salário, passando a ganhar R$ 3.360,00. Qual era o seu salário antes do aumento?', '[{"letra":"A","texto":"R$ 2.956,80","correta":false},{"letra":"B","texto":"R$ 2.900,00","correta":false},{"letra":"C","texto":"R$ 3.000,00","correta":true},{"letra":"D","texto":"R$ 3.200,00","correta":false},{"letra":"E","texto":"R$ 2.800,00","correta":false}]', 'C', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"R$ 3.000,00"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('23', 'Matemática e Raciocínio Lógico', 'A negação da proposição **"Todo servidor público é honesto"** é:', '[{"letra":"A","texto":"Nenhum servidor público é honesto.","correta":false},{"letra":"B","texto":"Existe servidor público que não é honesto.","correta":true},{"letra":"C","texto":"Todo servidor público é desonesto.","correta":false},{"letra":"D","texto":"Algum servidor público é honesto.","correta":false},{"letra":"E","texto":"Algum servidor público é desonesto.","correta":false}]', 'B', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"Existe servidor público que não é honesto."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('24', 'Matemática e Raciocínio Lógico', 'Considerando as proposições simples p: *O servidor estuda* e q: *O servidor é aprovado*, a proposição composta **"O servidor não estuda ou é aprovado"** é logicamente equivalente a:', '[{"letra":"A","texto":"p → q","correta":true},{"letra":"B","texto":"~p → q","correta":false},{"letra":"C","texto":"p → ~q","correta":false},{"letra":"D","texto":"~p → ~q","correta":false},{"letra":"E","texto":"q → p","correta":false}]', 'A', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"p → q"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('25', 'Matemática e Raciocínio Lógico', 'Em uma planilha do Excel, um funcionário deseja calcular a média dos valores contidos nas células de A1 a A5. A fórmula correta é:', '[{"letra":"A","texto":"=SOMA(A1;A5)","correta":false},{"letra":"B","texto":"=MÉDIA(A1:A5)","correta":true},{"letra":"C","texto":"=MÉDIA(A1;A5)","correta":false},{"letra":"D","texto":"=SOMA(A1:A5)/5","correta":false},{"letra":"E","texto":"=MÉDIA(A1,A5)","correta":false}]', 'B', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"=MÉDIA(A1:A5)"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('26', 'Matemática e Raciocínio Lógico', 'Se João é mais alto que Pedro, e Pedro é mais alto que Maria, então:', '[{"letra":"A","texto":"Maria é mais alta que João.","correta":false},{"letra":"B","texto":"João é mais baixo que Maria.","correta":false},{"letra":"C","texto":"João é mais alto que Maria.","correta":true},{"letra":"D","texto":"Pedro é o mais baixo de todos.","correta":false},{"letra":"E","texto":"Maria é a mais alta de todos.","correta":false}]', 'C', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"João é mais alto que Maria."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('27', 'Matemática e Raciocínio Lógico', 'Um capital de R$ 1.000,00 foi aplicado a juros simples de 5% ao mês por 6 meses. O montante obtido foi de:', '[{"letra":"A","texto":"R$ 1.300,00","correta":true},{"letra":"B","texto":"R$ 1.400,00","correta":false},{"letra":"C","texto":"R$ 1.200,00","correta":false},{"letra":"D","texto":"R$ 1.250,00","correta":false},{"letra":"E","texto":"R$ 1.500,00","correta":false}]', 'A', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"R$ 1.300,00"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('28', 'Matemática e Raciocínio Lógico', 'Em uma progressão aritmética, o primeiro termo é 5 e o décimo termo é 32. Qual é a razão dessa PA?', '[{"letra":"A","texto":"2","correta":false},{"letra":"B","texto":"2,5","correta":false},{"letra":"C","texto":"3","correta":true},{"letra":"D","texto":"3,5","correta":false},{"letra":"E","texto":"4","correta":false}]', 'C', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"3"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('29', 'Matemática e Raciocínio Lógico', 'Uma pesquisa mostrou que 60% dos servidores são a favor de um novo sistema. Se 120 servidores são a favor, qual o total de servidores?', '[{"letra":"A","texto":"150","correta":false},{"letra":"B","texto":"180","correta":false},{"letra":"C","texto":"200","correta":true},{"letra":"D","texto":"220","correta":false},{"letra":"E","texto":"240","correta":false}]', 'C', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"200"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('30', 'Matemática e Raciocínio Lógico', 'Dado o conjunto {10, 12, 12, 14, 16, 20}, a **mediana** é:', '[{"letra":"A","texto":"12","correta":false},{"letra":"B","texto":"13","correta":true},{"letra":"C","texto":"14","correta":false},{"letra":"D","texto":"14,5","correta":false},{"letra":"E","texto":"13,5","correta":false}]', 'B', 'De acordo com as propriedades numéricas e a estrutura lógica proposicional, a resolução aponta para a alternativa correta: **"13"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('31', 'Informática', 'Qual componente de hardware é responsável pelo armazenamento **permanente** de dados, mesmo com o computador desligado?', '[{"letra":"A","texto":"Memória RAM","correta":false},{"letra":"B","texto":"Processador (CPU)","correta":false},{"letra":"C","texto":"Placa-mãe","correta":false},{"letra":"D","texto":"HD (Disco Rígido) ou SSD","correta":true},{"letra":"E","texto":"Fonte de alimentação","correta":false}]', 'D', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"HD (Disco Rígido) ou SSD"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('32', 'Informática', 'O recurso do Word que permite enviar uma mesma correspondência para vários destinatários, personalizando campos como nome e endereço, é conhecido como:', '[{"letra":"A","texto":"Controle de alterações.","correta":false},{"letra":"B","texto":"Sumário automático.","correta":false},{"letra":"C","texto":"Mala direta.","correta":true},{"letra":"D","texto":"Estilos e formatação.","correta":false},{"letra":"E","texto":"Planilhas vinculadas.","correta":false}]', 'C', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"Mala direta."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('33', 'Informática', 'Qual das alternativas representa um endereço de e-mail **válido**?', '[{"letra":"A","texto":"usuario@servidor.com.br","correta":true},{"letra":"B","texto":"www.usuario@servidor.com","correta":false},{"letra":"C","texto":"usuario.servidor.com.br","correta":false},{"letra":"D","texto":"http://www.usuario.servidor.com","correta":false},{"letra":"E","texto":"usuario@servidor@com.br","correta":false}]', 'A', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"usuario@servidor.com.br"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('34', 'Informática', 'O protocolo que garante a segurança da transmissão de dados por meio de criptografia, identificado pelo "s" em "https", é o:', '[{"letra":"A","texto":"HTTP","correta":false},{"letra":"B","texto":"FTP","correta":false},{"letra":"C","texto":"SSL/TLS","correta":true},{"letra":"D","texto":"SMTP","correta":false},{"letra":"E","texto":"POP3","correta":false}]', 'C', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"SSL/TLS"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('35', 'Informática', 'No Windows, qual o atalho de teclado para **"desfazer"** a última ação?', '[{"letra":"A","texto":"Ctrl + C","correta":false},{"letra":"B","texto":"Ctrl + X","correta":false},{"letra":"C","texto":"Ctrl + V","correta":false},{"letra":"D","texto":"Ctrl + Z","correta":true},{"letra":"E","texto":"Ctrl + Y","correta":false}]', 'D', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"Ctrl + Z"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('36', 'Informática', 'Qual das opções é um exemplo de software de **navegação (browser)**?', '[{"letra":"A","texto":"Microsoft Excel","correta":false},{"letra":"B","texto":"Mozilla Firefox","correta":true},{"letra":"C","texto":"Windows Explorer","correta":false},{"letra":"D","texto":"Adobe Photoshop","correta":false},{"letra":"E","texto":"Avast Antivirus","correta":false}]', 'B', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"Mozilla Firefox"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('37', 'Informática', 'A extensão de arquivo **.pdf** é comumente associada a documentos criados por:', '[{"letra":"A","texto":"Microsoft Word","correta":false},{"letra":"B","texto":"Adobe Acrobat","correta":true},{"letra":"C","texto":"Microsoft PowerPoint","correta":false},{"letra":"D","texto":"Corel Draw","correta":false},{"letra":"E","texto":"Bloco de Notas","correta":false}]', 'B', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"Adobe Acrobat"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('38', 'Informática', 'O ato de criar uma cópia de segurança dos dados para recuperá-los em caso de perda é denominado:', '[{"letra":"A","texto":"Firewall","correta":false},{"letra":"B","texto":"Antivírus","correta":false},{"letra":"C","texto":"Backup","correta":true},{"letra":"D","texto":"Phishing","correta":false},{"letra":"E","texto":"Spam","correta":false}]', 'C', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"Backup"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('39', 'Informática', 'No Microsoft Excel, qual a função utilizada para contar células em um intervalo que atendem a um determinado critério?', '[{"letra":"A","texto":"=SOMA()","correta":false},{"letra":"B","texto":"=MÉDIA()","correta":false},{"letra":"C","texto":"=SE()","correta":false},{"letra":"D","texto":"=CONT.SE()","correta":true},{"letra":"E","texto":"=PROCV()","correta":false}]', 'D', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"=CONT.SE()"**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('40', 'Informática', 'Um **"cavalo de Troia" (Trojan)** é um tipo de:', '[{"letra":"A","texto":"Vírus de computador que se propaga automaticamente.","correta":false},{"letra":"B","texto":"Programa que monitora e bloqueia acessos não autorizados.","correta":false},{"letra":"C","texto":"Programa malicioso que se apresenta como legítimo, mas executa ações danosas.","correta":true},{"letra":"D","texto":"Ferramenta de criptografia de dados.","correta":false},{"letra":"E","texto":"Protocolo de segurança de rede.","correta":false}]', 'C', 'De acordo com o padrão técnico da ferramenta e as características de hardware/software, a resolução aponta para a alternativa correta: **"Programa malicioso que se apresenta como legítimo, mas executa ações danosas."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('41', 'Atualidades', 'O BRICS tem como principal característica:', '[{"letra":"A","texto":"Ser uma aliança militar para defesa do hemisfério sul.","correta":false},{"letra":"B","texto":"Ser um bloco econômico com moeda única e livre circulação de pessoas.","correta":false},{"letra":"C","texto":"Reunir países com economias em desenvolvimento de grande relevância no cenário global.","correta":true},{"letra":"D","texto":"Ser uma organização exclusivamente ambiental.","correta":false},{"letra":"E","texto":"Promover o isolamento comercial de seus membros.","correta":false}]', 'C', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Reunir países com economias em desenvolvimento de grande relevância no cenário global."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('42', 'Atualidades', 'A Política Nacional de Resíduos Sólidos (Lei nº 12.305/2010) estabelece a seguinte ordem de prioridade:', '[{"letra":"A","texto":"Reciclagem, reutilização, redução, tratamento e disposição final.","correta":false},{"letra":"B","texto":"Redução, reutilização, reciclagem, tratamento e disposição final.","correta":true},{"letra":"C","texto":"Tratamento, disposição final, redução, reutilização e reciclagem.","correta":false},{"letra":"D","texto":"Disposição final, tratamento, reciclagem, reutilização e redução.","correta":false},{"letra":"E","texto":"Reutilização, redução, tratamento, disposição final e reciclagem.","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Redução, reutilização, reciclagem, tratamento e disposição final."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('43', 'Atualidades', 'A LGPD (Lei nº 13.709/2018) visa a:', '[{"letra":"A","texto":"Aumentar o tempo de armazenamento de dados pessoais por empresas.","correta":false},{"letra":"B","texto":"Proteger os direitos fundamentais de liberdade e privacidade no tratamento de dados pessoais.","correta":true},{"letra":"C","texto":"Centralizar todos os dados dos cidadãos em um único banco de dados do governo.","correta":false},{"letra":"D","texto":"Criminalizar o uso da internet e das redes sociais.","correta":false},{"letra":"E","texto":"Restringir o acesso à informação pública.","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Proteger os direitos fundamentais de liberdade e privacidade no tratamento de dados pessoais."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('44', 'Atualidades', 'O conceito de **ESG** (Environmental, Social, and Governance) refere-se a:', '[{"letra":"A","texto":"Uma nova tecnologia de criptografia para transações financeiras.","correta":false},{"letra":"B","texto":"Um conjunto de práticas de sustentabilidade e governança que guiam as decisões de investimento.","correta":true},{"letra":"C","texto":"Um programa de combate à pobreza das Nações Unidas.","correta":false},{"letra":"D","texto":"Um tratado internacional sobre mudanças climáticas.","correta":false},{"letra":"E","texto":"Uma política de cotas para ingresso no serviço público.","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Um conjunto de práticas de sustentabilidade e governança que guiam as decisões de investimento."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('45', 'Atualidades', 'A reforma administrativa tem como um de seus principais objetivos:', '[{"letra":"A","texto":"Aumentar o número de cargos comissionados no primeiro escalão.","correta":false},{"letra":"B","texto":"Revisar as regras de estabilidade dos servidores públicos.","correta":true},{"letra":"C","texto":"Reduzir o controle sobre a administração pública indireta.","correta":false},{"letra":"D","texto":"Extinguir o regime jurídico estatutário para todos os servidores.","correta":false},{"letra":"E","texto":"Ampliar as hipóteses de acúmulo de cargos públicos.","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Revisar as regras de estabilidade dos servidores públicos."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('46', 'Atualidades', 'A **COP (Conferência das Partes)** é um evento relevante para discutir:', '[{"letra":"A","texto":"O acordo de livre comércio entre os países do Mercosul.","correta":false},{"letra":"B","texto":"O plano de metas de desenvolvimento econômico da ONU.","correta":false},{"letra":"C","texto":"O combate à corrupção na administração pública.","correta":false},{"letra":"D","texto":"As mudanças climáticas e o aquecimento global.","correta":true},{"letra":"E","texto":"A reforma do Conselho de Segurança da ONU.","correta":false}]', 'D', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"As mudanças climáticas e o aquecimento global."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('47', 'Atualidades', 'O **Mercosul** é um bloco econômico formado, inicialmente, por:', '[{"letra":"A","texto":"Brasil, Argentina, Uruguai e Venezuela.","correta":false},{"letra":"B","texto":"Brasil, Argentina, Paraguai e Uruguai.","correta":true},{"letra":"C","texto":"Brasil, Argentina, Chile e Bolívia.","correta":false},{"letra":"D","texto":"Brasil, Colômbia, Peru e Equador.","correta":false},{"letra":"E","texto":"Brasil, México, Paraguai e Uruguai.","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Brasil, Argentina, Paraguai e Uruguai."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('48', 'Atualidades', 'O conceito de **"Accountability"** na administração pública está relacionado à:', '[{"letra":"A","texto":"Centralização do poder decisório.","correta":false},{"letra":"B","texto":"Impessoalidade nos atos administrativos.","correta":false},{"letra":"C","texto":"Prestação de contas e responsabilização dos agentes públicos.","correta":true},{"letra":"D","texto":"Ampliação da discricionariedade dos gestores.","correta":false},{"letra":"E","texto":"Redução da transparência das informações.","correta":false}]', 'C', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Prestação de contas e responsabilização dos agentes públicos."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('49', 'Atualidades', 'O orçamento público federal é composto pelo PPA, pela LDO e pela:', '[{"letra":"A","texto":"Lei de Responsabilidade Fiscal (LRF).","correta":false},{"letra":"B","texto":"Lei Orçamentária Anual (LOA).","correta":true},{"letra":"C","texto":"Lei de Acesso à Informação (LAI).","correta":false},{"letra":"D","texto":"Consolidação das Leis do Trabalho (CLT).","correta":false},{"letra":"E","texto":"Constituição Federal (CF).","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"Lei Orçamentária Anual (LOA)."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('50', 'Atualidades', 'A **Taxa SELIC**, definida pelo COPOM do Banco Central, é:', '[{"letra":"A","texto":"O imposto sobre operações financeiras.","correta":false},{"letra":"B","texto":"A taxa básica de juros da economia brasileira.","correta":true},{"letra":"C","texto":"O índice oficial de inflação do país.","correta":false},{"letra":"D","texto":"A alíquota do Imposto de Renda.","correta":false},{"letra":"E","texto":"O valor do salário mínimo vigente.","correta":false}]', 'B', 'De acordo com o cenário global, ambiental e geopolítico recente, a resolução aponta para a alternativa correta: **"A taxa básica de juros da economia brasileira."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('51', 'Administração Pública', 'O princípio que veda a promoção pessoal de agentes públicos e exige que os atos sejam imputados ao órgão, e não à pessoa do servidor, é o princípio da:', '[{"letra":"A","texto":"Legalidade.","correta":false},{"letra":"B","texto":"Impessoalidade.","correta":true},{"letra":"C","texto":"Moralidade.","correta":false},{"letra":"D","texto":"Publicidade.","correta":false},{"letra":"E","texto":"Eficiência.","correta":false}]', 'B', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Impessoalidade."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('52', 'Administração Pública', 'O modelo de administração pública caracterizado pela impessoalidade, hierarquia rígida, meritocracia e excesso de formalismo é o modelo:', '[{"letra":"A","texto":"Gerencial.","correta":false},{"letra":"B","texto":"Burocrático.","correta":true},{"letra":"C","texto":"Empreendedor.","correta":false},{"letra":"D","texto":"Societal.","correta":false},{"letra":"E","texto":"Novo serviço público.","correta":false}]', 'B', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Burocrático."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('53', 'Administração Pública', 'A **FUNAI (Fundação Nacional do Índio)** é um exemplo de entidade integrante da:', '[{"letra":"A","texto":"Administração Direta.","correta":false},{"letra":"B","texto":"Administração Indireta, com personalidade jurídica de direito privado.","correta":false},{"letra":"C","texto":"Administração Indireta, com personalidade jurídica de direito público.","correta":true},{"letra":"D","texto":"Administração Indireta, como empresa pública.","correta":false},{"letra":"E","texto":"Administração Direta, como autarquia.","correta":false}]', 'C', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Administração Indireta, com personalidade jurídica de direito público."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('54', 'Administração Pública', 'De acordo com a Lei nº 9.784/1999, o prazo para interposição de **recurso administrativo** é de:', '[{"letra":"A","texto":"5 dias.","correta":false},{"letra":"B","texto":"10 dias.","correta":true},{"letra":"C","texto":"15 dias.","correta":false},{"letra":"D","texto":"30 dias.","correta":false},{"letra":"E","texto":"60 dias.","correta":false}]', 'B', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"10 dias."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('55', 'Administração Pública', 'O controle da Administração Pública realizado pelo próprio órgão sobre seus próprios atos é denominado controle:', '[{"letra":"A","texto":"Externo.","correta":false},{"letra":"B","texto":"Judicial.","correta":false},{"letra":"C","texto":"Legislativo.","correta":false},{"letra":"D","texto":"Interno.","correta":true},{"letra":"E","texto":"Social.","correta":false}]', 'D', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Interno."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('56', 'Administração Pública', 'A **A3P (Agenda Ambiental na Administração Pública)** tem como objetivo:', '[{"letra":"A","texto":"Criar novas áreas de preservação ambiental na Amazônia.","correta":false},{"letra":"B","texto":"Implantar práticas de sustentabilidade nos órgãos públicos.","correta":true},{"letra":"C","texto":"Regulamentar a contratação de empresas de saneamento.","correta":false},{"letra":"D","texto":"Fiscalizar o cumprimento do Código Florestal.","correta":false},{"letra":"E","texto":"Promover o desmatamento controlado.","correta":false}]', 'B', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Implantar práticas de sustentabilidade nos órgãos públicos."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('57', 'Administração Pública', 'O **TCU (Tribunal de Contas da União)** é responsável por exercer:', '[{"letra":"A","texto":"O controle jurisdicional sobre os atos do Poder Executivo.","correta":false},{"letra":"B","texto":"O controle externo da administração pública federal, auxiliando o Congresso Nacional.","correta":true},{"letra":"C","texto":"O controle interno de todos os poderes da República.","correta":false},{"letra":"D","texto":"A função de ouvidoria do Poder Judiciário.","correta":false},{"letra":"E","texto":"A defesa dos servidores públicos em processos administrativos.","correta":false}]', 'B', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"O controle externo da administração pública federal, auxiliando o Congresso Nacional."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('58', 'Administração Pública', 'Qual entidade da administração indireta tem seu capital formado **integralmente por recursos públicos**, mas pode adotar regime de direito privado?', '[{"letra":"A","texto":"Autarquia.","correta":false},{"letra":"B","texto":"Fundação Pública de direito público.","correta":false},{"letra":"C","texto":"Sociedade de Economia Mista.","correta":false},{"letra":"D","texto":"Empresa Pública.","correta":true},{"letra":"E","texto":"Órgão público.","correta":false}]', 'D', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Empresa Pública."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('59', 'Administração Pública', 'O **PPA (Plano Plurianual)** estabelece as diretrizes, objetivos e metas da administração federal para um período de:', '[{"letra":"A","texto":"1 ano.","correta":false},{"letra":"B","texto":"2 anos.","correta":false},{"letra":"C","texto":"3 anos.","correta":false},{"letra":"D","texto":"4 anos.","correta":true},{"letra":"E","texto":"5 anos.","correta":false}]', 'D', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"4 anos."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('60', 'Administração Pública', 'O princípio orçamentário que determina que a LOA não pode conter matéria estranha à previsão da receita e à fixação da despesa é o princípio da:', '[{"letra":"A","texto":"Unidade.","correta":false},{"letra":"B","texto":"Universalidade.","correta":false},{"letra":"C","texto":"Anualidade.","correta":false},{"letra":"D","texto":"Exclusividade.","correta":true},{"letra":"E","texto":"Equilíbrio.","correta":false}]', 'D', 'De acordo com os princípios administrativos vigentes e o modelo constitucional, a resolução aponta para a alternativa correta: **"Exclusividade."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('61', 'Regime Jurídico', 'O servidor público federal adquire estabilidade após:', '[{"letra":"A","texto":"2 anos de efetivo exercício, independentemente de avaliação.","correta":false},{"letra":"B","texto":"2 anos de efetivo exercício e aprovação em estágio probatório.","correta":false},{"letra":"C","texto":"3 anos de efetivo exercício e aprovação em avaliação especial de desempenho.","correta":true},{"letra":"D","texto":"3 anos de efetivo exercício, contados da posse.","correta":false},{"letra":"E","texto":"5 anos de efetivo exercício, comprovada a capacidade.","correta":false}]', 'C', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"3 anos de efetivo exercício e aprovação em avaliação especial de desempenho."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('62', 'Regime Jurídico', 'O retorno à atividade do servidor aposentado por invalidez, quando insubsistentes os motivos da aposentadoria, é denominado:', '[{"letra":"A","texto":"Reintegração.","correta":false},{"letra":"B","texto":"Recondução.","correta":false},{"letra":"C","texto":"Readaptação.","correta":false},{"letra":"D","texto":"Aproveitamento.","correta":false},{"letra":"E","texto":"Reversão.","correta":true}]', 'E', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Reversão."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('63', 'Regime Jurídico', 'Constitui **proibição** ao servidor público (Lei nº 8.112/1990):', '[{"letra":"A","texto":"Participar da administração de empresa privada, mesmo sem prejuízo de suas funções.","correta":true},{"letra":"B","texto":"Atender com presteza ao público, fornecendo as certidões requeridas.","correta":false},{"letra":"C","texto":"Exercer o direito de greve, nos termos da lei específica.","correta":false},{"letra":"D","texto":"Representar contra ilegalidade ou abuso de poder.","correta":false},{"letra":"E","texto":"Ser leal às instituições a que servir.","correta":false}]', 'A', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Participar da administração de empresa privada, mesmo sem prejuízo de suas funções."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.

💡 **Dica Extra:** Prazos, penalidades graves (demissão e cassação) e formas de provimento garantem a maioria das questões desse Título na Lei 8.112/90.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('64', 'Regime Jurídico', 'A penalidade de **suspensão** pode ser aplicada ao servidor por até:', '[{"letra":"A","texto":"30 dias.","correta":false},{"letra":"B","texto":"60 dias.","correta":false},{"letra":"C","texto":"90 dias.","correta":true},{"letra":"D","texto":"120 dias.","correta":false},{"letra":"E","texto":"180 dias.","correta":false}]', 'C', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"90 dias."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('65', 'Regime Jurídico', 'O servidor estável demitido por processo administrativo disciplinar poderá ser **reintegrado** ao cargo se:', '[{"letra":"A","texto":"Completar 5 anos de afastamento.","correta":false},{"letra":"B","texto":"A demissão for considerada nula por decisão administrativa ou judicial.","correta":true},{"letra":"C","texto":"O Presidente da República determinar sua reintegração.","correta":false},{"letra":"D","texto":"Houver vacância no cargo anterior.","correta":false},{"letra":"E","texto":"A sindicância que originou o processo for arquivada.","correta":false}]', 'B', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"A demissão for considerada nula por decisão administrativa ou judicial."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('66', 'Regime Jurídico', 'A lei que estabelece normas de conduta para agentes públicos e prevê sanções para atos de improbidade administrativa é a:', '[{"letra":"A","texto":"Lei nº 8.112/1990.","correta":false},{"letra":"B","texto":"Lei nº 9.784/1999.","correta":false},{"letra":"C","texto":"Lei nº 8.429/1992.","correta":true},{"letra":"D","texto":"Lei Complementar nº 101/2000.","correta":false},{"letra":"E","texto":"Decreto-Lei nº 2.848/1940.","correta":false}]', 'C', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Lei nº 8.429/1992."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('67', 'Regime Jurídico', 'Constitui ato de improbidade administrativa que **causa prejuízo ao erário**:', '[{"letra":"A","texto":"Receber vantagem econômica para praticar ato de ofício.","correta":false},{"letra":"B","texto":"Praticar ato visando a fim diverso do previsto na regra de competência.","correta":false},{"letra":"C","texto":"Revelar fato de que tem ciência em razão do cargo, sem justa causa.","correta":false},{"letra":"D","texto":"Permitir que outrem utilize bem público para fins particulares.","correta":true},{"letra":"E","texto":"Adquirir, para si, bens incompatíveis com a sua renda.","correta":false}]', 'D', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Permitir que outrem utilize bem público para fins particulares."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('68', 'Regime Jurídico', 'A licença ao servidor para tratar de **interesses particulares**:', '[{"letra":"A","texto":"É concedida com remuneração, por até 2 anos.","correta":false},{"letra":"B","texto":"Poderá ser concedida a qualquer tempo, independentemente do tempo de serviço.","correta":false},{"letra":"C","texto":"Não pode ser concedida ao servidor em estágio probatório.","correta":false},{"letra":"D","texto":"Poderá ser concedida por até 3 anos, sem remuneração.","correta":true},{"letra":"E","texto":"É concedida, automaticamente, por 1 ano, prorrogável por mais 1.","correta":false}]', 'D', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Poderá ser concedida por até 3 anos, sem remuneração."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('69', 'Regime Jurídico', 'A perda do cargo público por servidor estável pode ocorrer em razão de decisão judicial transitada em julgado, processo administrativo disciplinar, ou ainda por meio de:', '[{"letra":"A","texto":"Avaliação periódica de desempenho, na forma de lei complementar.","correta":true},{"letra":"B","texto":"Exoneração a pedido do próprio servidor.","correta":false},{"letra":"C","texto":"Posse em outro cargo inacumulável.","correta":false},{"letra":"D","texto":"Aposentadoria voluntária.","correta":false},{"letra":"E","texto":"Promoção na carreira.","correta":false}]', 'A', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Avaliação periódica de desempenho, na forma de lei complementar."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
INSERT INTO Questions (original_id, discipline, question, options, answer, explanation, banca, pegadinha, content_id) VALUES ('70', 'Regime Jurídico', 'O crime de **peculato** (art. 312 do Código Penal) consiste em:', '[{"letra":"A","texto":"Exigir, para si ou para outrem, vantagem indevida.","correta":false},{"letra":"B","texto":"Solicitar ou receber vantagem indevida para praticar ato de ofício.","correta":false},{"letra":"C","texto":"Apropriar-se o funcionário público de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo.","correta":true},{"letra":"D","texto":"Oferecer ou prometer vantagem indevida a funcionário público.","correta":false},{"letra":"E","texto":"Deixar de cumprir ordem superior, sem justa causa.","correta":false}]', 'C', 'De acordo com a literalidade da lei (ex. Lei 8.112/90) aliada à jurisprudência atual, a resolução aponta para a alternativa correta: **"Apropriar-se o funcionário público de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo."**.

Verifique as palavras-chave que conectam o enunciado à resposta e anule alternativas que distorçam o conhecimento aplicado.', 'ESAF', 'A ESAF tem a tradição de usar textos densos ou alternativas com ''cascas de banana'', alterando apenas verbos ou advérbios restritivos (como ''somente'', ''sempre'', ''nunca''). Leia os distratores com atenção!', 1);
COMMIT;
